services:
  evo:
    build: .
    container_name: evo
    restart: unless-stopped
    volumes:
      - ./evo:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evo.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.evo.entrypoints=websecure"
      - "traefik.http.routers.evo.tls.certresolver=letsencrypt"
      - "traefik.http.services.evo.loadbalancer.server.port=80"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
